name: PD Library
description: The Position Description Library is a tool that stores position descriptions across the enterprise. The tool allows those in HR position classification to create and maintain position descriptions, and allows read-only users, primarily managers and HR Specialists, to search for and view PDs.
contact:
  email: gsalabs@gsa.gov
languages:
  - javascript
  - apex
permissions:
  licenses:
    - URL: http://www.usa.gov/publicdomain/label/1.0/
      name: PD
  usageType: openSource
repositoryURL: https://github.com/GSA/PD-Library
organization: GSA
